apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-operator
  namespace: shell-operator
  labels:
    app: shell-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell-operator
  template:
    metadata:
      labels:
        app: shell-operator
    spec:
      serviceAccountName: shell-operator
      containers:
      - name: shell-operator
        image: ghcr.io/toddnni/toddnni/pe-automation-demo-2024-shell-operator:latest
        env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-token
              key: GIT_TOKEN
        - name: REPO_URL
          valueFrom:
            configMapKeyRef:
              name: repo-url
              key: repo-url
