---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shell-operator
rules:
- apiGroups: ["example.com"]
  resources: ["network-glue"
  verbs: ["get", "watch", "list"], "update"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shell-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shell-operator
subjects:
  - kind: ServiceAccount
    name: shell-operator
