---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-app
  namespace: asodemo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: asodemo
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-app
      #annotations:
        # Azure Workload Identity annotations
        #azure.workload.identity/client-id: "<clientId-of-UMI>"
    spec:
      serviceAccountName: go-app
      containers:
        - name: go-app
          image: ghcr.io/toddnni/toddnni/pe-automation-demo-2024:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SERVER
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: USERNAME
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: asodemo
spec:
  selector:
    app.kubernetes.io/name: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
