---
apiVersion: example.com/v1
kind: NetworkGlue
metadata:
  name: networkrule
  namespace: asodemo
spec:
  source:
    networkCIDR: 192.168.0.0/24
  target:
    networkCIDR: 192.168.1.0/24
    port: "443"
